### ISSUE TITLE
Add a YouTube video modal on clicking the play button in the service section.

### ISSUE THREAD

**Issue by sharifbubuka** [sharifbubuka/project__ui-design__landing-page#1]
**Issue:** The `react-modal-video` library seems to have a bug that does not permit a successful build during deployment to Vercel.

**Current hack:** I commented out the `react-modal-video ui` from the service-section component.

**Possible solutions:**
- Rectify the bug in the react-modal-video library.
- Use another library to implement similar functionality.
- Use native `HTML inline  <iframe> element` to implement custom similar functionality.

**Comment by AbdirahimAhmedNor** [comment]
I wanted to work on this but **do you want** the video to be **Played** when the action button is clicked `thank you`

**Comment by sharifbubuka** [comment]
> I wanted to work on this but **do you want** the video to be **Played** when the action button is clicked `thank you`

Yes, exactly. On clicking the play button, a centered modal should appear and start playing the video.

**Suggestion** 
I suggest you either use another library besides the `react-modal-video library` or, for an even better learning experience, implement it using the `<iframe>` element. You can read more about the <iframe> element [here](https://developer.mozilla.org/en-US/docs/web/html/element/iframe).

Below is an image of the possible end result.

![suggestion](https://user-images.githubusercontent.com/50671254/151664168-1432214e-aa00-4dba-bc0a-e8f0a6ed245a.PNG)

**Comment by myujjawal** [comment]
Hello, I also want to have a go at this. Thank you for the UI reference, I'll try to get all these done and reply to this thread.

**Comment by AbdirahimAhmedNor** [comment]
Assing to me I will do it

**Comment by myujjawal** [comment]
@sharifbubuka  Please review the changes if they are done as per your requirement. Do let me know if something else is needed.
Thank you
